format_version: 10
pipelines:
  BuildNodeApp:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-b6ed86b:
        git: https://github.com/SecuritySweet/node
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - Build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - install
                command: npm
                run_if: passed
